import React from 'react'
import Catalogo from './Catalogo'
import { Metadata } from 'next';

type Props = {}

export const metadata: Metadata = {
  title: "Catalogo - Muriel Entertainment",
  description: "Generated by create next app",
};

const page = (props: Props) => {
  return (
    <Catalogo />
  )
}

export default page