import React from 'react'
import SobreNosotros from './SobreNosotros'
import { Metadata } from 'next';

type Props = {}

export const metadata: Metadata = {
  title: "Sobre Nosotros - Muriel Entertainment",
  description: "Generated by create next app",
};

const page = (props: Props) => {
  return (
    <SobreNosotros />
  )
}

export default page