import type { Metadata } from "next";
import "./globals.css";
import NavBarComponent from "@/components/navbar/NavBarComponent";

export const metadata: Metadata = {
  title: "Inicio - Muriel Entertainment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative overflow-x-hidden">
        <NavBarComponent />
        <div className="relative">{children}</div>
      </body>
    </html>
  );
}
